### ISSUE TITLE
Wintersmith "preview" or "build" failed with Quick-Start  guide

### ISSUE THREAD

**Issue by jygastaud** [jnordberg/wintersmith#264]
Hi,

Follow the Quick-start guide, commands like `wintersmith preview` and `wintersmith build` failed because "site" dependencies are not automatically resolved.

In following example, "moment" library is not found.

```
starting preview server
using config file: /www/site/config.json

module.js:340
    throw err;
          ^
Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.require.resolve (module.js:384:19)
    at Environment.resolveModule (/usr/lib/node_modules/wintersmith/lib/core/environment.js:144:28)
    at Environment.loadModule (/usr/lib/node_modules/wintersmith/lib/core/environment.js:242:17)
    at Environment.setupLocals (/usr/lib/node_modules/wintersmith/lib/core/environment.js:113:35)
    at Environment.reset (/usr/lib/node_modules/wintersmith/lib/core/environment.js:85:19)
    at new Environment (/usr/lib/node_modules/wintersmith/lib/core/environment.js:60:12)
    at async.waterfall.paths (/usr/lib/node_modules/wintersmith/lib/cli/common.js:103:15)
    at fn (/usr/lib/node_modules/wintersmith/node_modules/async/lib/async.js:582:34)
    at Object._onImmediate (/usr/lib/node_modules/wintersmith/node_modules/async/lib/async.js:498:34)
```

Running a `npm install` inside the site directory solved the issue.

My thougtht is that is would be great if wintersmith preview (at least) can done the `npm install` in background if dependencies are not here.

At least, `npm install` should be mentionned into the Quick-start guide as follow

```
$ cd <path>
$ npm install
$ wintersmith preview
```

**Comment by mcronan** [comment]
Hi there, I am having this exact problem when I run 'wintersmith preview'. I tried the npm install but it does not make a difference. I am running it in a 'src' directory I created, to which I moved config.json, contents and templates, as per instructions when pushing your wintersmith to github pages. Is there another solution to this issue?
