### ISSUE TITLE
Can't build my site with 2.2.2

### ISSUE THREAD

**Issue by devgru** [jnordberg/wintersmith#292]
Can't build site with 2.2.2, here's the exception:

```
  building site
  using config file: /Users/devgru/Peers/Devgru/devg.ru/config.json
  rendering tree: ...
/usr/local/lib/node_modules/wintersmith/node_modules/async/lib/async.js:35
            if (called) throw new Error("Callback was already called.");
                        ^

Error: Callback was already called.
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/wintersmith/node_modules/async/lib/async.js:35:31)
    at WriteStream.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at WriteStream.emit (events.js:166:7)
    at finishMaybe (_stream_writable.js:468:14)
    at afterWrite (_stream_writable.js:347:3)
    at onwrite (_stream_writable.js:337:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fs.js:1872:5
    at FSReqWrap.strWrapper (fs.js:619:5)
```

**Comment by jnordberg** [comment]
I can't reproduce. Check your versions and post the verbose output with the -v flag
