### ISSUE TITLE
Wintersmith Preview Not Working

### ISSUE THREAD

**Issue by ToddAT** [jnordberg/wintersmith#310]
`http://localhost:8080/` isn't working in my browsers. I've double-checked that is correctly set up in the config file. Am I missing something (OS X)?

**Comment by jnordberg** [comment]
What's the output of `wintersmith preview -v`?

P.S, give this a read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html :)

**Comment by Manaus** [comment]
I'm getting the same error, 

```
starting preview server
  verbose creating environment - work directory: /Users/utente/Sites/wintersmith_site01
  using config file: /Users/utente/Sites/wintersmith_site01/config.json
  verbose config: {"locals":{"url":"http://localhost:8890","name":"The Wintersmith's blog","owner":"Someone","description":"Ramblings of an immor(t)al demigod"},"plugins":["./plugins/paginator.coffee"],"require":{"moment":"moment","_":"underscore","typogr":"typogr"},"jade":{"pretty":true},"markdown":{"smartLists":true,"smartypants":true},"paginator":{"perPage":3},"contents":"./contents","ignore":[],"templates":"./templates","views":null,"output":"./build","baseUrl":"/","hostname":null,"port":8080,"_fileLimit":40,"_restartOnConfChange":true,"__filename":"/Users/utente/Sites/wintersmith_site01/config.json","_cliopts":{"verbose":true,"v":true,"quiet":false,"q":false,"version":false,"V":false,"help":false,"h":false,"c":"./config.json","C":null},"verbose":true,"v":true,"quiet":false,"q":false,"version":false,"V":false,"help":false,"h":false,"c":"./config.json","C":null}
  verbose loading module 'moment' available in locals as 'moment'
  verbose loading module 'underscore' available in locals as '_'
  verbose loading module 'typogr' available in locals as 'typogr'
  verbose watching config file /Users/utente/Sites/wintersmith_site01/config.json for changes
  verbose starting preview server
  verbose loading default plugin: page
  verbose loading default plugin: jade
  verbose registering template plugin JadeTemplate that handles: **/*.jade
  verbose loading default plugin: markdown
  verbose registering content plugin MarkdownPage that handles: **/*.*(markdown|mkd|md)
  verbose registering content plugin JsonPage that handles: **/*.json
  verbose loading plugin: ./plugins/paginator.coffee

error listen EADDRINUSE
  at exports._errnoException (util.js:746:11)
  at Server._listen2 (net.js:1129:14)
  at listen (net.js:1155:10)
  at net.js:1253:9
  at dns.js:85:18
  at process._tickCallback (node.js:355:11)


    code: 'EADDRINUSE'
    errno: 'EADDRINUSE'
    syscall: 'listen'
```

I tried out all sorts of ports but 80: 8080, 8888, 8889, 8890, proxy, no proxy... 
Using MacOs

**Comment by jnordberg** [comment]
Your port is in use, changing the locals.url does not affect what port the server is run on, thats just metadata for the site. You need to pass `--port`
