### ISSUE TITLE
wintersmith build - crash on ubuntu 16.04 

### ISSUE THREAD

**Issue by antirek** [jnordberg/wintersmith#321]
install now and try build existing project - crash.
![2017-01-13 12-28-38](https://cloud.githubusercontent.com/assets/324436/21919870/1a8fd2e0-d990-11e6-97cb-a9b808b6d06b.png)

ubuntu 16.04, nodejs 7.4.0

**Comment by jnordberg** [comment]
Can you post the output of `wintersmith build -vv`

**Comment by antirek** [comment]
`````sh
sergey@sergey-300E5C:~/Projects/mobilon_docs$ wintersmith build -vv
  building site
  verbose creating environment - work directory: /home/sergey/Projects/mobilon_docs
  using config file: /home/sergey/Projects/mobilon_docs/config.json
  verbose config: {"locals":{"url":"http://antirek.github.io/mobilon_docs/build","name":"Mobilon Docs","owner":"Someone","description":"Документация для пользователей, а также их родителей"},"require":{"moment":"moment","_":"underscore","typogr":"typogr"},"jade":{"pretty":true},"markdown":{"smartLists":true,"smartypants":true},"baseUrl":"/","contents":"./contents","ignore":[],"plugins":[],"templates":"./templates","views":null,"output":"./build","hostname":null,"port":8080,"_fileLimit":40,"_restartOnConfChange":true,"__filename":"/home/sergey/Projects/mobilon_docs/config.json","_cliopts":{"X":false,"verbose":true,"v":true,"quiet":false,"q":false,"version":false,"V":false,"help":false,"h":false,"c":"./config.json","C":null},"X":false,"verbose":true,"v":true,"quiet":false,"q":false,"version":false,"V":false,"help":false,"h":false,"c":"./config.json","C":null}
  verbose loading module 'moment' available in locals as 'moment'
  silly loading module: moment
/usr/lib/node_modules/wintersmith/node_modules/async/dist/async.js:837
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /usr/lib/node_modules/wintersmith/node_modules/async/dist/async.js:837:32
    at /usr/lib/node_modules/wintersmith/lib/core/utils.js:48:18
    at nextTask (/usr/lib/node_modules/wintersmith/node_modules/async/dist/async.js:5070:14)
    at /usr/lib/node_modules/wintersmith/node_modules/async/dist/async.js:5064:13
    at apply (/usr/lib/node_modules/wintersmith/node_modules/async/dist/async.js:21:25)
    at /usr/lib/node_modules/wintersmith/node_modules/async/dist/async.js:56:12
    at /usr/lib/node_modules/wintersmith/node_modules/async/dist/async.js:840:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
`````

**Comment by antirek** [comment]
Sorry, before use I  must do 'npm install' for plugins.

**Comment by jnordberg** [comment]
Thanks and nothing to apologise for! I actually think this might be a bug so I'm reopening this. The log should show that a module is missing not an obscure error about a callback being called twice when this happens.

**Comment by adius** [comment]
This error also occurs while using yarn instead of npm.

**Comment by adius** [comment]
I get this error when I use yarn instead of npm

**Comment by dagoss** [comment]
Same issue as @adius. I got this error when I used Yarn. Deleted the node_modules dir, ran `npm install` and everything worked fine. With yarn, I ended up with async 2.1.4; with npm, 2.1.5.

**Comment by jnordberg** [comment]
Should have better error reporting now. Tried to reproduce with yarn but worked fine for me. Feel free to open up another issue about it if the problem persists

**Comment by adius** [comment]
@jnordberg I'm still having this issue! With npm everything works fine ...

**Comment by jnordberg** [comment]
@adius create another issue with steps to reproduce and I'll have a look

**Comment by adius** [comment]
Sure. Here you go: https://github.com/jnordberg/wintersmith/issues/327
