### ISSUE TITLE
wintersmith preview not working

### ISSUE THREAD

**Issue by Mmarzex** [jnordberg/wintersmith#55]
Everytime I try to use the wintersmith preview command I keep getting this error

   wintersmith preview
   starting preview server
   path.exists is now called `fs.exists`.
    using config file: /Users/maxmarze/sandbox/node.js/wintersmith/beta/config.json
    server running on: http://localhost:8080/

```
events.js:66
    throw arguments[1]; // Unhandled 'error' event
                   ^
Error: listen EADDRINUSE
at errnoException (net.js:769:11)
at Server._listen2 (net.js:909:14)
at listen (net.js:936:10)
at Server.listen (net.js:985:5)
at run (/usr/local/lib/node_modules/wintersmith/lib/server.js:123:14)
at Object.async.forEach     (/usr/local/lib/node_modules/wintersmith/node_modules/async/lib/async.js:82:20)
at loadPlugins (/usr/local/lib/node_modules/wintersmith/lib/index.js:38:16)
at async.apply (/usr/local/lib/node_modules/wintersmith/node_modules/async/lib/async.js:532:23)
at async.iterator.fn   (/usr/local/lib/node_modules/wintersmith/node_modules/async/lib/async.js:517:34)
at async.waterfall.wrapIterator   (/usr/local/lib/node_modules/wintersmith/node_modules/async/lib/async.js:441:34)
```

**Comment by browncolyn** [comment]
I'm using Wintersmith for the first time. As a developer I make use of a lot of different ports for a variety of projects. I used the `---port` flag to start the server with a new port other than the default. This works fine, however, when I save a file and wintersmith attempts to restart the server, I get an `EADDRINUSE` use error again. It honored my custom port option for initializing the server but not for restarts, it seems.
